
# Get libdir from
execute_process (COMMAND HepMC3-config --includedir
  OUTPUT_VARIABLE HEPMC_INCDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process (COMMAND HepMC3-config --libdir
  OUTPUT_VARIABLE HEPMC_LIBDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process (COMMAND HepMC3-config --prefix
  OUTPUT_VARIABLE HEPMCROOT OUTPUT_STRIP_TRAILING_WHITESPACE)

include_directories(${HEPMC_INCDIR})
LIST(APPEND EXTRA_LINK_DIRS ${HEPMC_LIBDIR})
SET(HEPMC_LIBS HepMC3 HepMC3rootIO)
SET(HEPMC_LIBFLAGS "-L ${HEPMC_LIBDIR} -lHepMC3 -lHepMC3rootIO")
LIST(APPEND EXTRA_LIBS ${HEPMC_LIBS})
